# 서버 설정
server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slisli
        username: root
        password: my1234

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

security:
    jwt:
        token:
            secret-key: "생성된 secret key를 여기에 넣으세요"
            expire-length: 3600000
    oauth2:
        client:
            registration:
                google:
                    client-id: YOUR_GOOGLE_CLIENT_ID
                    client-secret: YOUR_GOOGLE_CLIENT_SECRET
                    redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
